### ISSUE TITLE
Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by jramoyo** [substack/node-browserify#1029]
I am getting this error when running browserify from the command line:

```
path.js:313
        throw new TypeError('Arguments to path.resolve must be strings');
        ^
TypeError: Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at /usr/lib/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:97:37
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
```

I'm running browserify@7.0.2

```
npm list -g browserify
/usr/lib
└── browserify@7.0.2
```

**Comment by FractalizeR** [comment]
@yazla  I think it's too old to be used.

**Comment by yazla** [comment]
@FractalizeR , well yeah, but who cares, it works and that is what we need.)))

**Comment by terinjokes** [comment]
Is this still an issue with 9.0.x? What platform are you on?

**Comment by yazla** [comment]
@terinjokes , didn't test on that, need to find some time to test, will try to do that soon. I am on windows 8.

**Comment by FractalizeR** [comment]
I moved to webpack. Tired of struggling with browserify. Sorry.

**Comment by jmm** [comment]
In addition to @terinjokes' questions, please see [How to report issues with browserify](https://github.com/substack/node-browserify/wiki/How-to-report-issues-with-browserify), particularly the `example` section. How can this be reproduced? What is the CLI command you're using? What's in the file(s) you're bundling?

**Comment by neurosnap** [comment]
So in my particular case, a node module's `main` attribute in `package.json` was an array and not a string.

The way I found this out was going to where the error originated in my node_modules and then did `console.log(pkg.main)` right above it.

**Comment by SergioMorchon** [comment]
Same here with `gulp.dest("my_path/my_fbundle.js")`...

**Comment by jmm** [comment]
@SergioMorchon That doesn't sound like a browserify issue. And it looks as though you may be attempting to pass a file name to `gulp.dest()` when it should be a directory name.

**Comment by SergioMorchon** [comment]
Using a folder reproduces the same error. My real example:
``` typescript
return browserify("build/project.js").bundle().pipe(gulp.dest("release"));
```

**Comment by jmm** [comment]
@SergioMorchon FYI, if it's a browserify issue you almost certainly can (and in those cases definitely should) reproduce it without additional layers like gulp in the picture. The problem you're having is that `gulp.dest()` takes vinyl files as input and you're piping the output of `b.bundle()` (not a vinyl file) to it. In that case you should probably just `.pipe(fs.createWriteStream('my_path/my_bundle.js'))`. If you're really using gulp for something then you can do `.bundle().pipe(require('vinyl-source-stream')('my_bundle.js')).pipe(gulp.dest('my_path'))`.

**Comment by SergioMorchon** [comment]
@jmm Thank you a lot!
Using fs worked for me :+1:

**Comment by jmm** [comment]
@SergioMorchon Great, you're welcome!
