### ISSUE TITLE
Fails on d3-geo-projection

### ISSUE THREAD

**Issue by mattcg** [substack/node-browserify#1142]
```bash
git clone git@github.com:d3/d3-geo-projection.git
cd d3-geo-projection/
npm install browserify
./node_modules/.bin/browserify .
```

The following is the output:

```
SyntaxError: Line 4: Unexpected token . while parsing [redacted]/d3-geo-projection/index.js while parsing file: [redacted]/d3-geo-projection/index.js
    at Stream.end ([redacted]/d3-geo-projection/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at _end ([redacted]/d3-geo-projection/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end ([redacted]/d3-geo-projection/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend ([redacted]/d3-geo-projection/node_modules/browserify/node_modules/module-deps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
    at [redacted]/d3-geo-projection/node_modules/browserify/node_modules/module-deps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)
```

`index.js` appears to have no syntax errors and `d3.geo.projection.js` works fine when loaded directly in a browser.

I'm running node v0.10.36.

**Comment by nikku** [comment]
This is an issue with `brfs`. It cannot handle

```
var fs = require("fs"),
    path = require("path");
```

Separate the two assignments via `;` and you are good.

Cf. substack/brfs#28

**Comment by mattcg** [comment]
Thanks, that workaround will do for now!
