### ISSUE TITLE
version >= 9.0.3 fails with gulp and vinyl-transform

### ISSUE THREAD

**Issue by ibc** [substack/node-browserify#1213]
Node 0.12.0.

```
    "browserify": "^9.0.8",
    "gulp": "git+https://github.com/gulpjs/gulp.git#4.0",
    "vinyl-transform": "^1.0.0"
```

gulpfile.js:

```
javascript
gulp.task('browserify', function() {
	var browserified = vinyl_transform(function(filename) {
		var b = browserify(filename, {
			standalone: pkg.name
		});
		return b.bundle();
	});

	var src = pkg.main;
	return gulp.src(src)
		.pipe(browserified)
		.pipe(header(banner, banner_options))
		.pipe(rename(builds.uncompressed))
		.pipe(gulp.dest('dist/'));
});
```

This just worked with previous versions of browserify. But now I get:

```
[15:58:42] 'browserify' errored after 68 ms
[15:58:42] TypeError: undefined is not a function
    at Producer.ondata (_stream_readable.js:540:20)
    at Producer.emit (events.js:107:17)
    at Producer.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by terinjokes** [comment]
This was an error in the gulp recipes that relied on internal behavior. (See #1191 and #1044). Please see the updated gulp guides:

* [Browserify + Uglify2](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-uglify-sourcemap.md#browserify--uglify2-with-sourcemaps)
* [Browserify + Globs](https://github.com/gulpjs/gulp/blob/4d35560d9e2e992037886897c671518cfe49fd7f/docs/recipes/browserify-with-globs.md#browserify--globs)

**Comment by ibc** [comment]
Thanks a lot.
