### ISSUE TITLE
Error when using `exposeAll` with external

### ISSUE THREAD

**Issue by englercj** [substack/node-browserify#1292]
If I do something like the following:

```js
browserify({ debug: true, exposeAll: true })
    .external('_env/messages')
    .add('./src/my/entry.js')
```

This is because on [this line](https://github.com/substack/node-browserify/blob/10.2.3/index.js#L413) `row.deps['_env/messages']` is `false`, which throws this error:

```
path.js:146
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.win32.relative (path.js:270:14)
    at ...\node_modules\browserify\index.js:413:44
```

If I add `if (!row.deps[key]) return;` just above the path() call, then the bundle builds without error. I'm not 100% sure that this is the correct fix, so I posted an issue instead of a PR.

**Comment by jmm** [comment]
@englercj Thanks for the report. I'd say let's sort out the situation with `exposeAll` in general (e.g. #1293, #1296) and then figure out what to do here.

**Comment by wenbing** [comment]
:+1:
