### ISSUE TITLE
--node with require / module

### ISSUE THREAD

**Issue by mattdesl** [substack/node-browserify#1340]
Are there any plans to support more native-like `require` and `module` globals when using `browserify --node` ? 

For example:

`index.js`
```js
console.log(require.resolve('url'))
```

Prints `url` with node:
```sh
node index.js
```

However, throws an error with browserify:
```js
browserify index.js --node | node
```

```
TypeError: Object function (e){var n=t[o][1][e];return s(n?n:e)} has no method 'resolve'
    at Object.<anonymous> ([stdin]:2:21)
    at s ([stdin]:1:254)
    at e ([stdin]:1:425)
    at [stdin]:1:443
    at Object.<anonymous> ([stdin]-wrapper:6:22)
    at Module._compile (module.js:456:26)
    at evalScript (node.js:536:25)
    at Socket.<anonymous> (node.js:154:11)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
```

**Comment by substack** [comment]
Maybe require.resolve can fall back through to whatever `require` is already defined. This is how `require()` works across multiple bundles already.
