### ISSUE TITLE
Null reference exception when generating source maps

### ISSUE THREAD

**Issue by Flaise** [substack/node-browserify#1343]
My project which browserifies correctly when source maps are left out of the build process fails to build when I turn on source maps. It throws this exception:

    <project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\util.js:37

        var match = aUrl.match(urlRegexp);
                        ^
    TypeError: Cannot read property 'match' of null
        at urlParse (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\util.js:37:21)
        at normalize (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\util.js:86:15)
        at Array.map (native)
        at SourceMapConsumer.BasicSourceMapConsumer (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\source-map-consumer.js:311:23)
        at new SourceMapConsumer (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\source-map\lib\source-map\source-map-consumer.js:26:9)
        at module.exports (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\lib\mappings-from-map.js:10:18)
        at Combiner._addExistingMap (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\index.js:70:18)
        at Combiner.addFile (<project>\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\index.js:113:49)
        at DestroyableTransform.write [as _transform] (<project>\node_modules\browserify\node_modules\browser-pack\index.js:63:23)
        at DestroyableTransform.Transform._read (<project>\node_modules\browserify\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
        at DestroyableTransform.Transform._write (<project>\node_modules\browserify\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)

The exception is raised by one of Browserify's dependencies but it's not clear to me whether it's a bug in the dependency or if Browserify is giving it bad inputs. My code invoking Browserify is as follows:

    var browserify = require('browserify')

    browserify({debug: true, entries: "..."})
        .bundle(function(err, src) {
            // ...
        })

The exception is raised before the above callback is invoked.

**Comment by galexy** [comment]
+1
