### ISSUE TITLE
Wrong relative path generation 

### ISSUE THREAD

**Issue by ananas7** [substack/node-browserify#1406]
Steps to reproduce:

 - Create a file with one line: `var apipub = require('apipub/client');`
 - Compile with `browserify index.js > bundle.js`

```
C:\Users\i.lomtev\Desktop\bug>browserify index.js > bundle.js
Error: Cannot find module '..\..\..\..\..\..\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\index.js' from 'C:\Users\i.lomtev\Desktop\bug\node_modules\apipub\node_modules\simple-websocket'
    at C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

Expected:

 - Path should be `..\..\..\..\..\..\Users\i.lomtev\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\index.js` or `..\..\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\index.js` 

Current behaviour:

 - Browserify tries to find that module in the folder `..\..\..\..\..\..\AppData\Roaming\npm\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\` which doesn't exist.

**Comment by oakio** [comment]
Same problem https://github.com/substack/node-browserify/issues/1408
