### ISSUE TITLE
Problem with request module

### ISSUE THREAD

**Issue by oakio** [substack/node-browserify#1408]
Could not build javascript (using require module) application with browserify because:
```
Error: Cannot find module '../C:\Users\oakio\AppData\Roaming\nvm\v0.12.7\node_modules\browserify\node_modules\insert-module-globals\node_modules\is-buffer\index.js' from 'c:\Projects\reqtest\node_modules\request\node_modules\combined-stream\lib'
    at C:\Users\oakio\AppData\Roaming\nvm\v0.12.7\node_modules\browserify\node_modules\resolve\lib\async.js:55:21
    at load (C:\Users\oakio\AppData\Roaming\nvm\v0.12.7\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\oakio\AppData\Roaming\nvm\v0.12.7\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\oakio\AppData\Roaming\nvm\v0.12.7\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Steps to reproduce:
Create app.js with simple content:
```
var req = require('request');
req.get('http://google.com', function (e, r) {
});
```
Next create package.json:
```
{
  "name": "reqtest",
  "version": "0.0.1",
  "description": "Test",
  "main": "app.js",
  "dependencies": {
    "babelify": "^6.3.0",
    "request": "^2.65.0"
  },
  "browserify": {
    "transform": [
      "babelify"
    ]
  }
}
```
And run 
```browserify app.js > bundle.js```

Enviroment:
>OS: Windows 7 x64 
>nodejs: v0.12.7 
>npm: v2.11.3
>browserify v11.2.0
>request v2.65.0

[Related](http://stackoverflow.com/questions/33217411/browserify-cannot-find-module-insert-module-globals-node-modules-is-buffer-inde)

**Comment by airtonix** [comment]
same here.

```
[16:42:25] Browserify Error: Cannot find module 'coffeeify' from '/home/zenobius/Projects/USA/usa002/client'
```

path should be : '/home/zenobius/Projects/USA/usa002/'

```
node:  4.2.1
npm:  2.14.7
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic
```
