### ISSUE TITLE
Cannot rebrowserify bundle with querystring module

### ISSUE THREAD

**Issue by rahatarmanahmed** [substack/node-browserify#1449]
I'm in a situation where I have module A that provides a browserified build on npm. I have another module B that depends on module A and also provides a browserified build.

I found an issue with having module A requiring the [querystring](https://github.com/substack/querystring) module. You can reproduce with the following steps:

```shell
npm install querystring
echo "var qs = require('querystring');" > index.js
browserify index.js -o bundle.js
echo "var bundle = require('./bundle');" > index.js
browserify index.js -o bundle2.js
```

This returns the error:
```shell
Error: Cannot find module './decode' from '/Users/rahat/Downloads/temp'
    at /Users/rahat/.nvm/versions/node/v0.12.7/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/Users/rahat/.nvm/versions/node/v0.12.7/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/rahat/.nvm/versions/node/v0.12.7/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /Users/rahat/.nvm/versions/node/v0.12.7/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by rahatarmanahmed** [comment]
Nevermind, I realize that it's trying to parse the first bundle on the second browserify command, trying to resolve the require statements. The reason other dependencies of module A worked before is because they had no require statements
