### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 11 reset listeners added. Use emitter.setMaxListeners() to increase limit.

### ISSUE THREAD

**Issue by Emnalyeriar** [substack/node-browserify#1475]
I defined my gulp browserify task like [here](https://github.com/gulpjs/gulp/blob/master/docs/recipes/fast-browserify-builds-with-watchify.md). I only added tsify plugin in bundle function:
`b.plugin(tsify).bundle()`
And after about 3-5 rebundles I get this error:
```
(node) warning: possible EventEmitter memory leak detected. 11 reset listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Browserify.addListener (events.js:239:17)
    at tsify (D:\xampp\htdocs\project\node_modules\tsify\index.js:23:4)
    at Browserify.plugin (D:\xampp\htdocs\project\node_modules\browserify\index.js:349:9)
    at Browserify.bundleDev (D:\xampp\htdocs\project\gulp\tasks\scripts.js:31:15)
    at emitOne (events.js:77:13)
    at Browserify.emit (events.js:169:7)
    at notify [as _onTimeout] (D:\xampp\htdocs\project\node_modules\watchify\index.js:149:15)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by zoubin** [comment]
Probably you should apply the plugin outside the `bundle` function.

```js
b.plugin(tsify)

function bundle() {}
```

**Comment by Emnalyeriar** [comment]
Earlier today I found in watchify docs that its possible to set plusings as browserify options. So i defined them like this:
```
var b = browserify({
  cache: {},
  packageCache: {},
  plugin: [watchify, tsify]
});
```
And this solved this problem for me but I think that your solution would also be good, thanks!
