### ISSUE TITLE
failure to resolve transform when run from subdirectory within project

### ISSUE THREAD

**Issue by tvald** [substack/node-browserify#1542]
When running browserify + transforms from a subdirectory within a project, it will fail with the following error:
```
C:path\subdir> npm run browserify -t hyperxify main.js > bundle.js  # [1]

Error: Cannot find module 'C:\path\hyperxify' from 'C:\path'
    at C:\path\node_modules\resolve\lib\async.js:55:21
    at load (C:\path\node_modules\resolve\lib\async.js:
69:43)
    at onex (C:\path\node_modules\resolve\lib\async.js:
92:31)
    at C:\path\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

# [1] NB: browserify binary is aliased as a script, due to local installation of browserify
```

I've verified that the transform is resolved if I run browserify from the root of the project.  I've also verified that the `resolve()` module will properly find the transform (in this case, hyperxify) if called directly from a script in the subdirectory.

**Comment by tvald** [comment]
more testing:
**ok** `node ..\node_modules\browserify\bin\cmd.js -t hyperxify main.js`
**ok** `..\node_modules\.bin\browserify -t hyperxify main.js`
**fail** `npm run browserify -t hyperxify main.js`

So this can probably be closed as npm doing something stupid with the path or working directory that isn't worth tracking down.
