### ISSUE TITLE
Invalid Mapping Source Map Generator Issue

### ISSUE THREAD

**Issue by jadesym** [substack/node-browserify#1593]
I have the following gulpfile that I am using to run browserify, but I am having some weird issues:

Using browserify (version 12.0.1) results in the following error:

```
/home/ubuntu/.pm2/repos/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275
        throw new Error('Invalid mapping: ' + JSON.stringify({
        ^

Error: Invalid mapping: {"generated":{"line":155,"column":7},"source":"App.js","original":{},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping] (/home/ubuntu/.pm2/repos/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:275:15)
    at SourceMapGenerator_addMapping [as addMapping] (/home/ubuntu/.pm2/repos/node_modules/inline-source-map/node_modules/source-map/lib/source-map/source-map-generator.js:105:14)
    at /home/ubuntu/.pm2/repos/node_modules/inline-source-map/index.js:40:15
    at Array.forEach (native)
    at Generator.addMappings (/home/ubuntu/.pm2/repos/node_modules/inline-source-map/index.js:38:12)
    at Combiner._addExistingMap (/home/ubuntu/.pm2/repos/node_modules/combine-source-map/index.js:33:18)
    at Combiner.addFile (/home/ubuntu/.pm2/repos/node_modules/combine-source-map/index.js:58:12)
    at DestroyableTransform.write [as _transform] (/home/ubuntu/.pm2/repos/node_modules/browser-pack/index.js:63:23)
    at DestroyableTransform.Transform._read (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:279:12)
    at writeOrBuffer (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:266:5)
    at DestroyableTransform.Writable.write (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:211:11)
    at DestroyableTransform.ondata (/home/ubuntu/.pm2/repos/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:572:20)
```

I have tried a few things such as removing all the node_modules and reinstalling, and that seems to work sometimes. Then when I try running it again to recreate the files, I get the same error again. I've looked in several places trying to find what the issue may be, but I'm not really sure and I don't know if this is the right place to ask this question.

Here is the file I am currently using.
```
/*
 |--------------------------------------------------------------------------
 | This file was taken from the following tutorial:
 | http://sahatyalkabov.com/create-a-character-voting-app-using-react-nodejs-mongodb-and-socketio/#step-8-react-routes-server-side
 |--------------------------------------------------------------------------
 */


var gulp = require('gulp');
var gutil = require('gulp-util');
var gulpif = require('gulp-if');
var autoprefixer = require('gulp-autoprefixer');
var cssmin = require('gulp-cssmin');
var less = require('gulp-less');
var concat = require('gulp-concat');
var plumber = require('gulp-plumber');
var buffer = require('vinyl-buffer');
var source = require('vinyl-source-stream');
var babelify = require('babelify');
var browserify = require('browserify');
var watchify = require('watchify');
var uglify = require('gulp-uglify');
var sourcemaps = require('gulp-sourcemaps');

var production = process.env.NODE_ENV === 'production';

var dependencies = [
  'alt',
  'react',
  'react-dom',
  'react-router',
  'underscore'
];

/*
 |--------------------------------------------------------------------------
 | Combine all JS libraries into a single file for fewer HTTP requests.
 |--------------------------------------------------------------------------
 */
gulp.task('vendor', function() {
  return gulp.src([
    'bower_components/jquery/dist/jquery.js',
    'bower_components/bootstrap/dist/js/bootstrap.js',
    'bower_components/magnific-popup/dist/jquery.magnific-popup.js',
    'bower_components/toastr/toastr.js'
  ]).pipe(concat('vendor.js'))
    .pipe(gulpif(production, uglify({ mangle: false })))
    .pipe(gulp.dest('public/js'));
});

/*
 |--------------------------------------------------------------------------
 | Compile third-party dependencies separately for faster performance.
 | For performance reasons, NPM modules specified in the dependencies array
 | are compiled and bundled separately. As a result, bundle.js recompiles
 | a few hundred milliseconds faster.
 |--------------------------------------------------------------------------
 */
gulp.task('browserify-vendor', function() {
  return browserify()
    .require(dependencies)
    .bundle()
    .pipe(source('vendor.bundle.js'))
    .pipe(buffer())
    .pipe(gulpif(production, uglify({ mangle: false })))
    .pipe(gulp.dest('public/js'));
});

/*
 |--------------------------------------------------------------------------
 | Compile only project files, excluding all third-party dependencies.
 | Compiles and bundles just the app files, without any external modules
 | like react and react-router.
 |
 | Generates a single file called bundle.js
 |--------------------------------------------------------------------------
 */
gulp.task('browserify', ['browserify-vendor'], function() {
  return browserify({ entries: 'app/main.js', debug: true })
    .external(dependencies)
    .transform(babelify, { presets: ['es2015', 'react'] })
    .bundle()
    .pipe(source('bundle.js'))
    .pipe(buffer())
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(gulpif(production, uglify({ mangle: false })))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('public/js'));
});

/*
 |--------------------------------------------------------------------------
 | Same as browserify task, but will also watch for changes and re-compile.
 | Essentially the same task as above but it will also listen for changes
 | and re-compile bundle.js.
 |--------------------------------------------------------------------------
 */
gulp.task('browserify-watch', ['browserify-vendor'], function() {
  var bundler = watchify(browserify({ entries: 'app/main.js', debug: true }, watchify.args));
  bundler.external(dependencies);
  bundler.transform(babelify, { presets: ['es2015', 'react'] });
  bundler.on('update', rebundle);
  return rebundle();

  function rebundle() {
    var start = Date.now();
    return bundler.bundle()
      .on('error', function(err) {
        gutil.log(gutil.colors.red(err.toString()));
      })
      .on('end', function() {
        gutil.log(gutil.colors.green('Finished rebundling in', (Date.now() - start) + 'ms.'));
      })
      .pipe(source('bundle.js'))
      .pipe(buffer())
      .pipe(sourcemaps.init({ loadMaps: true }))
      .pipe(sourcemaps.write('.'))
      .pipe(gulp.dest('public/js/'));
  }
});

/*
 |--------------------------------------------------------------------------
 | Compile LESS stylesheets.
 | Compiles LESS stylesheets and automatically adds browser prefixes if necessary.
 |--------------------------------------------------------------------------
 */
gulp.task('styles', function() {
  return gulp.src('app/stylesheets/main.less')
    .pipe(plumber())
    .pipe(less())
    .pipe(autoprefixer())
    .pipe(gulpif(production, cssmin()))
    .pipe(gulp.dest('public/css'));
});

/*
 |--------------------------------------------------------------------------
 | Re-compiles LESS stylesheets on file changes.
 |--------------------------------------------------------------------------
 */
gulp.task('watch', function() {
  gulp.watch('app/stylesheets/**/*.less', ['styles']);
});

/*
 |--------------------------------------------------------------------------
 | Runs all of the above tasks and starts watching for file changes.
 |--------------------------------------------------------------------------
 */
gulp.task('default', ['styles', 'vendor', 'browserify-watch', 'watch']);

/*
 |--------------------------------------------------------------------------
 | Runs all of the above tasks then exits.
 |--------------------------------------------------------------------------
 */
gulp.task('build', ['styles', 'vendor', 'browserify']);

```

**Comment by abhisekpaul** [comment]
same issue for me.any update?

**Comment by AlexanderSuv** [comment]
Try this:
.transform(babelify, { presets: ['es2015', 'react'] }) -> .transform(babelify, { presets: ['es2015', 'react'], sourceMaps: false })

**Comment by richardnoel** [comment]
I tried the same problem, the solution was to modify my code, that for some reason "Source Map Generator", could not interpret my code and change it, I put a console.log  in the mthod of file /node_modules/source-map/lib/source-map/source-map-generator.js

  SourceMapGenerator.prototype.addMapping =
    function SourceMapGenerator_addMapping(aArgs) {
      var generated = util.getArg(aArgs, 'generated');
      var original = util.getArg(aArgs, 'original', null);
      var source = util.getArg(aArgs, 'source', null);
      var name = util.getArg(aArgs, 'name', null);
      console.log(aArgs);
      if (!this._skipValidation) {
        this._validateMapping(generated, original, source, name);
      }

      if (source != null && !this._sources.has(source)) {
        this._sources.add(source);
      }

      if (name != null && !this._names.has(name)) {
        this._names.add(name);
      }

      this._mappings.add({
        generatedLine: generated.line,
        generatedColumn: generated.column,
        originalLine: original != null && original.line,
        originalColumn: original != null && original.column,
        source: source,
        name: name
      });
    };
and print In which line fails, to modify the code
