### ISSUE TITLE
Bad error message for invalid `"browserify"` entry in `package.json`

### ISSUE THREAD

**Issue by bowsersenior** [substack/node-browserify#1594]
I had an invalid `"browserify"` entry in my `package.json` and kept getting a confusing `Error: path must be a string` error message. I would expect a message like, `Invalid format for "browserify" entry in package.json`.

This could be the root cause of #884 (closed since it could not be reproduced).

See below for details on how to reproduce:

```bash
$ browserify --version
13.0.1
$ cat package.json 
{
  "browserify": {
    "transform": [
      [
        [
          "babelify",
          {
            "presets": [
              "es2015"
            ]
          }
        ]
      ]
    ]
  },
  "devDependencies": {
    "browserify": "^13.0.1"
  }
}
$ cat index.js
a = 1;                                                                                                                                          $ browserify index.js 
Error: path must be a string
    at /private/tmp/browserify-bug/node_modules/resolve/lib/async.js:16:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
$ rm package.json 
$ browserify index.js
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
a = 1;
},{}]},{},[1]);
```

To clarify, the problem is the extra array inside the `"transform"` value:

```json
  "browserify": {
    "transform": [
      [
        [
          "babelify",
          {
            "presets": [
              "es2015"
            ]
          }
        ]
      ]
    ]
  }
```

When I fix the entry as follows, `browserify` works fine:

```json
  "browserify": {
      "transform": [
        [
          "babelify", {
            "presets": [
              "es2015"
            ]
          }
        ]
      ]
    }
```

**Comment by goto-bus-stop** [comment]
seems useful--this would have to be addressed in https://github.com/browserify/module-deps which is where the package.json `browserify.transform` key is read.
