### ISSUE TITLE
Browserify with adbkit: Cannot find module './src/adb'

### ISSUE THREAD

**Issue by ddaaggeett** [substack/node-browserify#1598]
My Node script:
`var adb = require("adbkit");`

upon running in terminal:
`browserify script.js -o bundle.js`

is resulting:
```
Error: Cannot find module './src/adb' from '/home/[user]/app/node_modules/adbkit'
at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
at Object.oncomplete (fs.js:107:15)
```

I have 'adbkit' installed globally and locally in my Express app, as demonstrated by my dependencies:

```
"dependencies": {
    "adbkit": "^2.4.1",
    ...
}
```

Similarly to [this](https://github.com/openstf/adbkit-apkreader/issues/2), for adbkit, adbkit-monkey, and adbkit-logcat I attempted to force each of their respective index.js files to reference `./lib/adb`, `./lib/monkey`, and `./lib/logcat` as it is for the JS environment.  Hardcoding to the correct directories then allows the bundle to be created, but then when I run the bundle with `node bundle.js` the following error occurs: `TypeError: Cannot read property 'prototype' of undefined`

What can I do for this to work?

**Comment by ddaaggeett** [comment]
For adbkit, adbkit-monkey, and adbkit-logcat I attempted to force each of their respective index.js files to reference `./lib/adb`, `./lib/monkey`, and `./lib/logcat` as it is for the JS environment. This does not do the trick.
