### ISSUE TITLE
Error: Cannot find module './args'

### ISSUE THREAD

**Issue by davidbarratt** [substack/node-browserify#1609]
I'm trying to execute Mocha:
```
./node_modules/.bin/mocha --compilers js:babel-register --require babel-polyfill
```

but I get the following error:
```
Error: Cannot find module './args'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dbarratt/sites/gc-ui/src/node_modules/.bin/browserify:6:9)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dbarratt/sites/gc-ui/src/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/dbarratt/sites/gc-ui/src/node_modules/.bin/sha.js:3:18)
    at Module._compile (module.js:541:32)
    at Module._extensions..js (module.js:550:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dbarratt/sites/gc-ui/src/node_modules/babel-register/lib/node.js:156:7)
```

**Comment by ian** [comment]
+1 getting same issue

**Comment by ian** [comment]
Updating `browserify` to `13.1.0` fixed for me.

**Comment by davidbarratt** [comment]
For me, I had a `mocha.opts` file that had this:
```
. --recursive
```
when it should have been:
```
--recursive
```
removing the `.` resolved my issue. :)
