### ISSUE TITLE
Cannot re-export everything using ES6

### ISSUE THREAD

**Issue by ernestoalejo** [substack/node-browserify#1651]
Imports and exports are working correctly when using babelify, but if I re-export everything from another file:
```js
export * from './foo';
```

browserify fails when trying to find the dependencies before babelify can convert them:
```
Error: Parsing file /app/common/scripts/mycomponent/index.js: 'import' and 'export' may appear only with 'sourceType: module' (3:0)
    at Deps.parseDeps (/app/node_modules/browserify/node_modules/module-deps/index.js:454:28)
    at fromSource (/app/node_modules/browserify/node_modules/module-deps/index.js:391:44)
    at /app/node_modules/browserify/node_modules/module-deps/index.js:385:17
    at ConcatStream.<anonymous> (/app/node_modules/browserify/node_modules/concat-stream/index.js:36:43)
    at emitNone (events.js:72:20)
    at ConcatStream.emit (events.js:166:7)
    at finishMaybe (/app/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:475:14)
    at endWritable (/app/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:485:3)
    at ConcatStream.Writable.end (/app/node_modules/browserify/node_modules/concat-stream/node_modules/readable-stream/lib/_stream_writable.js:455:41)
    at DuplexWrapper.onend (/app/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:504:10)
    at DuplexWrapper.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at DuplexWrapper.emit (events.js:166:7)
    at endReadableNT (/app/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:926:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

For reference this is the call in the gulpfile:
```js
  var b = browserify({
      entries: [`projects/${project}/scripts/app.js`],
      paths: ['common/scripts'],
      debug: true,
    });

    var plugins = [
      'transform-runtime',
      'transform-object-rest-spread',
      replaceVue,
    ];
    return b
      .transform('babelify', {
        presets: ['es2015'],
        extensions: ['.js', '.vue'],
        plugins: plugins,
      })
      .bundle()
      .on('error', function(err) {
        throw err;
      })
      .pipe(source('app.js'))
      .pipe(gulp.dest('tmp/assets/static/scripts'));
```

**Comment by saidmoya12** [comment]
Try with babelify

https://github.com/babel/babelify

```
  browserify({
    entries: [`projects/${project}/scripts/app.js`],
    paths: ['common/scripts'],
    debug: true,
  })..transform(babelify);

```
