### ISSUE TITLE
Very Strange Behaviour with Async and Await

### ISSUE THREAD

**Issue by BamItsPixel** [substack/node-browserify#1748]
I am trying to compile a large program into a single file.

I am using `Node 8.0.0`.

`browserify --node index.js > out.js`

This command works if I don't use `async` and `await`.

How can one make it work? Node 8 supports async/await out of the box and if I do `node index.js`, it just works.

Thanks!

**Comment by BamItsPixel** [comment]
Hello, apologies for not getting back to you for a while.

I get no error with this.

However, I kid you not, when I append my code, _commented out_, I get this error:

> osxlocal:server pixel$ browserify --node --detect-globals=false index.js > vanilla_server.js
> SyntaxError: Unexpected token (2:6) while parsing /Users/pixel/Desktop/WebGL/src/server/index.js while parsing file: /Users/pixel/Desktop/WebGL/src/server/index.js
>     at DestroyableTransform.end [as _flush] (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:96:21)
>     at DestroyableTransform.<anonymous> (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
>     at Object.onceWrapper (events.js:312:19)
>     at emitNone (events.js:105:13)
>     at DestroyableTransform.emit (events.js:207:7)
>     at prefinish (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
>     at finishMaybe (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)
>     at endWritable (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:485:3)
>     at DestroyableTransform.Writable.end (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:455:41)
>     at DestroyableTransform.onend (/usr/local/lib/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:495:10)

My code is as follows (it's for a game server): https://pastebin.com/raw/1aMn9Pvv

It's all commented out! When I remove the commented out code, browserify works.

**Comment by BamItsPixel** [comment]
<never mind- I was on version 13>
