### ISSUE TITLE
Browserify dependency needs cloneWithProps

### ISSUE THREAD

**Issue by ArtanisAce** [substack/node-browserify#1751]
Hi, recently I've upgraded my project from React 0.14 to 15, and as you might know, on this last version 'cloneWithProps' is deprecated and you must use 'cloneElement' instead. Well, browserify install 'module-deps' as a dependency, and this one installs 'browser-resolve', which installs 'resolve' and this one needs 'react-addons-clone-with-props'. Is there a way to fix this with a new version of `browserify`, or how should I approach this?

This is the output of my gulp build:

`Error: Cannot find module 'react/lib/cloneWithProps' from '/home/ppmiron/Development/Project/node_modules/react-addons-clone-with-props'
    at /home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/ppmiron/Development/Project/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
`

**Comment by tsalud** [comment]
Having the same problem. Any solution?

**Comment by ljharb** [comment]
The resolve module has no dependencies in anything react-related. The issue is that you have something in your dep graph requiring it.
