### ISSUE TITLE
Error when `browserField: false` and `process` is used

### ISSUE THREAD

**Issue by kumavis** [substack/node-browserify#1835]
> Error: Cannot find module '_process' from '/Users/xyz/dev/metamask-extension/mascara/src'

```
╭─xyz@xyzs-MacBook-Pro ~/dev/browserify-test  
╰─$ echo 'console.log(process.env)' > index.js
╭─xyz@xyzs-MacBook-Pro ~/dev/browserify-test  
╰─$ browserify --no-browser-field index.js > bundle.js
Error: Cannot find module '_process' from '/Users/xyz/dev/browserify-test'
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
    at processDirs (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
    at ondir (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
    at load (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
    at onex (/Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
    at /Users/xyz/.nvm/versions/node/v8.9.4/lib/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:152:21)
```

**Comment by marriskleinert** [comment]
Same problem here...
Any workarounds for that?

**Comment by marriskleinert** [comment]
Found a mistake in our code. We imported process but we should've used the global Node.js variable.
Maybe also a solution in your case? @kumavis

**Comment by goto-bus-stop** [comment]
> Found a mistake in our code. We imported process but we should've used the global Node.js variable.

it's not really a mistake on your end, since both are valid in Node.js. but only the global works in browserify at the moment, yes.

The OP in this issue was using the global variable but it's giving this error anyway when combined with the `--no-browser-field` flag.

**Comment by marriskleinert** [comment]
Alright, thanks for the explanation :)
