### ISSUE TITLE
Unable to get require alias working with Gulp.

### ISSUE THREAD

**Issue by Gree1** [substack/node-browserify#1836]
I am using gulp with browserify, and I cannot get require to use an alias.  It looked like the command should be:

```
browserify({
        entries: 'cli/main.js',
        debug: true,
        require: [['./cli/main.js', {expose: 'cli'}]],
        transform: [babelify]})
        .bundle()
        .pipe(source('cli.js'))
        .pipe(gulp.dest('./app/compiled'));
```

However this throws an error:
```
Error: Cannot find module 'cli' from 'C:\Users\Owner\workspace\ui\crimson\war'
    at C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Owner\workspace\ui\crimson\war\node_modules\browser-resolve\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

The problem is that I have no way to access this library externally from the main code without an alias.  If I just use:  **require: './cli/main.js'**, the full path needed will be different depending on who compiles it and is therefore not possible. I have been trying to figure out if I can get alias to work, but to no avail.

gulpfile.js details:
The gulpfile.js has a task:

gulp.task('cli', cliCompile);

where cliCompile returns the above browserify.

**Comment by goto-bus-stop** [comment]
Iirc the require option doesn't support specifying options. You have to use the .require() function instead

**Comment by Gree1** [comment]
so:

   ```
 var b = browserify({
        entries: 'cli/main.js',
        debug: true,
        transform: [babelify]});
    b.require('./cli/main.js', {expose: 'cli'});
    return b.bundle()
        .pipe(source('cli.js'))
        .pipe(gulp.dest('./app/compiled'));
```
This seems to be working.  Could the documentation on external referencing state this more clearly?  It was not obvious to me what I needed to do.
