### ISSUE TITLE
test failure: tests/external.js: undefined is not a function

### ISSUE THREAD

**Issue by andrewrk** [substack/node-browserify#693]
```
not ok test/external.js ................................. 0/1
    Command: "/usr/bin/nodejs external.js"
    TAP version 13
    not ok 1 test/external.js
      ---
        exit:    8
        stderr:  |
          /home/andy/dev/node-browserify/test/external.js:12
                  vm.runInNewContext(
                     ^
          TypeError: undefined is not a function
              at Object../x.js (evalmachine.<anonymous>:2:28)
              at s (evalmachine.<anonymous>:1:302)
              at e (evalmachine.<anonymous>:1:473)
              at evalmachine.<anonymous>:1:491
              at /home/andy/dev/node-browserify/test/external.js:12:12
              at /home/andy/dev/node-browserify/index.js:299:22
              at /home/andy/dev/node-browserify/index.js:299:22
              at /home/andy/dev/node-browserify/index.js:327:13
              at ConcatStream.<anonymous> (/home/andy/dev/node-browserify/node_modules/concat-stream/index.js:32:43)
              at ConcatStream.EventEmitter.emit (events.js:92:17)
        command: "/usr/bin/nodejs external.js"
      ...
    
    1..1
    # tests 1
    # fail  1
```
```
$ node -v
v0.10.26
$ head -n 3 package.json 
{
  "name": "browserify",
  "version": "3.32.1",
```

**Comment by terinjokes** [comment]
Looks to have been resolved at some point. :)

```
ok test/external.js ..................................... 3/3
```
