### ISSUE TITLE
Gracefully handle files that cannot be required

### ISSUE THREAD

**Issue by cvan** [substack/node-browserify#901]
I have a file (`settings.js`) that is compiled by browserify. I want it to require a `settings_local.js` file only if if it exists. From the documentation and source code, I can't figure out if this is possible. This is what I currently have:

``` js
var settings_local = {};
try {
  settings_local = require('./settings_local.js');
} catch (e) {
}
```

This is the error I get:

``` bash
events.js:82
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module './settings_local.js' from '/opt/galaxy.js-mobile-gamepad/src/js'
    at /opt/galaxy.js-mobile-gamepad/node_modules/browserify/node_modules/resolve/lib/async.js:42:25
    at load (/opt/galaxy.js-mobile-gamepad/node_modules/browserify/node_modules/resolve/lib/async.js:60:43)
    at /opt/galaxy.js-mobile-gamepad/node_modules/browserify/node_modules/resolve/lib/async.js:66:22
    at /opt/galaxy.js-mobile-gamepad/node_modules/browserify/node_modules/resolve/lib/async.js:21:47
    at Object.oncomplete (fs.js:97:15)
```

**Comment by stevenpetryk** [comment]
:+1:

**Comment by terinjokes** [comment]
Based on how browserify works, I don't think it is possible. Can you resolve the use cases by using the `envify` transform to allow settings to be overridden locally?

**Comment by jmm** [comment]
You could probably create a transform to implement that, e.g. using [benbria/browserify-transform-tools](https://github.com/benbria/browserify-transform-tools). That'll let you replace an entire `require(...)` expression, so you could either make it require some different module that just exports an empty object or something, or replace the whole expression with an empty object or whatever. So in your transform you can check the file system and do the appropriate thing.

You might also be able to do this with my [pathmodify](https://www.npmjs.com/package/pathmodify) plugin by doing something like this (exact implementation depends how many of these you have / how dynamic you need it to be / how specific [e.g. you can check parent module pathname if necessary]):

```js
var pathmodify = require('pathmodify');

browserify()
  .plugin(pathmodify(), {mods: [
    plugin.mod.re(/(^|/)settings_local.js$/, function (rec) {
      // Check file system
      if (exists) return rec;
      else return {id: "path_to_some_file_that_exports_empty_object"}
    })
  ]})
```

**Comment by jmm** [comment]
*Maybe* you could even check the file system for that module before bundling and call `b.ignore()` on it if it doesn't exist. I'm not sure how the path matching / resolution works with that though. Perhaps the `require()`'d module that you want to ignore has to actually successfully resolve to a file before you can ignore it.

**Comment by jscissr** [comment]
I have the same problem browserifying `ws`. It contains the following file:

```js
try {
  module.exports = require('utf-8-validate');
} catch (e) {
  module.exports = require('./Validation.fallback');
}
```

I think it should be possible for browserify to detect `require`s inside a `try`/`catch`, and automatically `exclude()` it if it can't be found (not `ignore()`, because then no error is thrown and you don't get the fallback).

Do you think it's possible? I would try to make a PR.

**Comment by pizza2code** [comment]
Trying to make a bundle for node (rather than for a browser), and 3rd-party modules' optional dependencies are causing browserify errors in exactly this fashion.

That, combined with the difficulty in finding API options for Node bundling, implies that bundling outside of the browser is a faint, barely-supported afterthought.  :/

**Comment by hawkerboy7** [comment]
Hi, I have been running into this issue as well and I a different solution approach which I feel is relatively easy to make and does not break backwards compatibility. I may be quite wrong though :) 

I think making Browserify detect a `require` within a `try` `catch` block would be a bit hard to make whilst keep everything working the way you'd expect it to work and remain backwards compatible. Also the `catch (e)` block would now somehow contain a server side error, while the bundle file is only executed by the browser, so you'd need browserify to add some error object containing possible try catch errors (with stack) and send it to the client which may not be ideal for production-environments.

What it boils down to I believe is that we'd like to be able to make the `browserify.bundle()` function continue the bundling process instead of breaking when a file is required that does not exsist / is not found. However this is not always the case for every file. So instead of hardcoding the list of 'silently-continue-if-not-found' files server-side using the option `ignoreMissing`, perhaps the following could be added to the `require` function?

```javascript
var settings = {a: 1, b: 2};
var item = require("./item");
var localSettings = require.dontBreakIfNotFound("./local-settings");
if (localSettings !== undefined) {
  settings = localSettings;
};
```

With this setup:
- if the file `item.js` is not found the bundle breaks (the way Browserify already works).
- if the file `local-settings.js` is not found the bundle would just return `undefined` (or `null`) but not break allowing you to optionally have the file `local-settings.js`.

Except for the terrible name `dontBreakIfNotFound` :smirk: what do you think of this setup @jmm and @jscissr or does this already exists?
